# Generated by Django 3.2.7 on 2023-03-05 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('mode', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=20)),
                ('start', models.CharField(max_length=50)),
                ('end', models.CharField(max_length=50)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('no_seats', models.IntegerField()),
                ('total_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('gender', models.CharField(max_length=10)),
                ('User_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('train_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel.transport')),
            ],
        ),
    ]
