# Generated by Django 3.2.7 on 2023-03-05 10:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_alter_transport_total_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='transport',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 5, 16, 19, 2, 720846)),
        ),
        migrations.AddField(
            model_name='transport',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2023, 3, 5, 16, 19, 2, 720846)),
        ),
        migrations.AlterField(
            model_name='transport',
            name='end_time',
            field=models.TimeField(default=datetime.datetime(2023, 3, 5, 16, 19, 2, 720846)),
        ),
        migrations.AlterField(
            model_name='transport',
            name='start_time',
            field=models.TimeField(default=datetime.datetime(2023, 3, 5, 16, 19, 2, 720846)),
        ),
    ]
